version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: book_catalog_db_4ak3_user
      POSTGRES_PASSWORD: 98XkzhZSWkCcwkHt2ZIVZtDOBAtIvSZt
      POSTGRES_DB: book_catalog_db
    ports:
      - "5432:5432"

  book_catalog:
    build: ./book_catalog
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://book_catalog_db_4ak3_user:98XkzhZSWkCcwkHt2ZIVZtDOBAtIvSZt@dpg-crgfg75svqrc73f1oabg-a.oregon-postgres.render.com/book_catalog_db_4ak3
    depends_on:
      - db

  inventory_management:
    build: ./inventory_management
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://book_catalog_db_4ak3_user:98XkzhZSWkCcwkHt2ZIVZtDOBAtIvSZt@dpg-crgfg75svqrc73f1oabg-a.oregon-postgres.render.com/book_catalog_db_4ak3
    depends_on:
      - db
